// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlAFHBJunLnwoynegxhIyeWh4QY2w12U',
    appId: '1:1094675370056:web:dfea46be5d44caa005887d',
    messagingSenderId: '1094675370056',
    projectId: 'chat-app-flutter-cfbce',
    authDomain: 'chat-app-flutter-cfbce.firebaseapp.com',
    storageBucket: 'chat-app-flutter-cfbce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOi5qUtQVwEDf678hyKc4Gs2l1kIpVlk',
    appId: '1:1094675370056:android:1990eecf5affbe3705887d',
    messagingSenderId: '1094675370056',
    projectId: 'chat-app-flutter-cfbce',
    storageBucket: 'chat-app-flutter-cfbce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8nv6dkiVX4DdXr19pjBwfuhySpoobofs',
    appId: '1:1094675370056:ios:d555af9fc880383d05887d',
    messagingSenderId: '1094675370056',
    projectId: 'chat-app-flutter-cfbce',
    storageBucket: 'chat-app-flutter-cfbce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8nv6dkiVX4DdXr19pjBwfuhySpoobofs',
    appId: '1:1094675370056:ios:d555af9fc880383d05887d',
    messagingSenderId: '1094675370056',
    projectId: 'chat-app-flutter-cfbce',
    storageBucket: 'chat-app-flutter-cfbce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArlAFHBJunLnwoynegxhIyeWh4QY2w12U',
    appId: '1:1094675370056:web:77d745863820d80205887d',
    messagingSenderId: '1094675370056',
    projectId: 'chat-app-flutter-cfbce',
    authDomain: 'chat-app-flutter-cfbce.firebaseapp.com',
    storageBucket: 'chat-app-flutter-cfbce.firebasestorage.app',
  );
}
